environment:
  name: sandbox
  project: my-sandbox
  validation-type: dev
  selected:
    - modules/foo
    - modules/bar
    - modules/baz
    - modules/zoo

variables:
  environment: Sandbox
  modules:
    id_prefix: id

    foo:
      x: 1

    bar:
      x: 2
