name: msgraft
description: Your worst nightmare
inputs:
  access-token:
    description: "Microsoft Entra access token"
    required: true
runs:
  using: docker
  image: Dockerfile
  args: ["-AccessToken", "${{ inputs.access-token }}"]
