on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    - test
jobs:
  mergeback:
    runs-on: ubuntu-latest
    environment: automergeback
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0  # need to fetch at least to merge base
    - uses: actions/create-github-app-token@v3
      id: app-token
      with:
        # required
        client-id: '${{ vars.APP_CLIENT_ID }}'
        private-key: '${{ secrets.APP_PRIVATE_KEY }}'
        permission-contents: write
        permission-pull-requests: write
    - name: Git authentication
      id: get-user-id
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
        GH_APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
      run: |
        gh_user_id="$(gh api "/users/${GH_APP_SLUG}[bot]" --jq .id)"
        git config --global user.name "${GH_APP_SLUG}[bot]"
        git config --global user.email "${gh_user-id}+${GH_APP_SLUG}[bot]@users.noreply.github.com"
        gh auth setup-git
    - env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: |
        set -euo pipefail
        source_branch="${GITHUB_REF#refs/heads/}"  # strip refs/heads/prefix
        .github/workflows/automergeback.sh "$source_branch"
