name: Config review

on:
  pull_request_review:
    types:
      - submitted
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - config.sandbox.yaml

permissions:
  contents: read
  pull-requests: read

jobs:
  config_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          app-id: ${{ vars.CONFIG_REVIEWER_APP_ID }}
          private-key: ${{ secrets.CONFIG_REVIEWER_PRIVATE_KEY }}

      - name: Default branch checkout
        uses: actions/checkout@v4

      - name: Fetch head and base of pull request
        env:
          BASE_SHA: "${{ github.event.pull_request.base.sha }}"
          HEAD_SHA: "${{ github.event.pull_request.head.sha }}"
        run: |
          git fetch origin "$BASE_SHA" "$HEAD_SHA"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: pip install
        run: pip install .

      - name: foo
        env:
          BASE_SHA: "${{ github.event.pull_request.base.sha }}"
          HEAD_SHA: "${{ github.event.pull_request.head.sha }}"
          TMPDIR: "${{ runner.temp }}"
          GH_TOKEN: "${{ steps.app-token.outputs.token }}"
          GITHUB_REPOSITORY: "${{ github.repository }}"
          PR_NUMBER: "${{ github.event.pull_request.number }}"
        run: |
          set -euo pipefail

          declare -a changed_settings
          adv config-diff \
            <(git show "${BASE_SHA}:config.sandbox.yaml") \
            <(git show "${HEAD_SHA}:config.sandbox.yaml") \
            --map :config.sandbox.yaml/: \
            --map variables/::variables/ \
            --null-terminate \
            > "${TMPDIR}/changed_settings"
          readarray -t -d '\0' changed_settings <"${TMPDIR}/changed_settings"

          if [[ "${#changed_settings[@]}" -eq 0 ]]; then
            echo "no config changes to approve" >&2
            exit 0
          fi

          cat "${TMPDIR}/changed_settings" \
          | xargs -0 adv codeowners \
          | sed -E 's/^@//' \
          | while read -r approver; do
              if [[ $approver == */* ]]; then
                # organization team
                org="$(echo "$approver" | cut -d/ -f 1)"
                team_slug="$(echo "$approver" | cut -d/ -f 2)"
                echo "Fetching members of team $approver..." >&2
                gh api "/orgs/${org}/teams/${team_slug}/members" \
                  --paginate \
                  --jq '.[].login'
              else
                # user
                echo "$approver"
              fi
            done \
          | LC_ALL=C sort -u \
          > "${TMPDIR}/user_approvers"

          echo "Users that can approve config changes" >&2
          cat "${TMPDIR}/user_approvers" \
          | xargs -d'\n' -I{} printf "  %s\n" {} \
          >&2

          echo "Fetching list of users that have approved the pull request" >&2
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            "/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER}/reviews" \
            --paginate \
            --jq '.[] | select(.state == "APPROVED") | .user.login' \
          | LC_ALL=C sort -u \
          | tee "${TMPDIR}/approved_by" \
          | xargs -d'\n' -I{} printf "  %s\n" {} \
          >&2

          readarray -t owner_approvers < <(
            grep -x -F \
              "$(cat "${TMPDIR}/user_approvers")" \
              "${TMPDIR}/approved_by"
          )
          owner_approved=
          for owner_approver in "${owner_approvers[@]}"; do
            echo "approved by owner ${owner_approver}" >&2
            owner_approved=yes
          done
          if [[ -z $owner_approved ]]; then
            echo "not approved by any owners" >&2
            exit 1
          fi

