---
name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  - push
  - workflow_dispatch
permissions:
  id-token: write
  contents: read
  packages: read
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "fromJson('[false]').*"
        if: fromJson('[false]').*
      - run: echo "fromJson('[1]').*"
        if: fromJson('[1]').*
      - run: echo "fromJson('[]').*"
        if: fromJson('[]').*
      - run: echo fromJson('[]') == fromJson('[]')
        if: fromJson('[]') == fromJson('[]')
      - run: echo fromJson('[]') == fromJson('[1]')
        if: fromJson('[]') == fromJson('[1]')
      - run: echo fromJson('[]') == fromJson('[1]')
        if: fromJson('[]') == fromJson('[1]')
      - run: echo join(fromJson('[]'), '') == ''
        if: join(fromJson('[]'), '') == ''
      - run: echo join(fromJson('[1]'), '') == ''
        if: join(fromJson('[1]'), '') == ''
      - uses: actions/checkout@v4
      - name: 'Az CLI login'
        uses: azure/login@8c334a195cbb38e46038007b304988d888bf676a
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Run az commands'
        id: access-token
        run: |
          az account get-access-token \
              --resource-type ms-graph \
              -o tsv \
              --query accessToken \
            | xargs -I{} echo access_token={} \
            > "$GITHUB_OUTPUT"
      - run: find /home/runner/work/github-action-adventures
      - name: 'List groups'
        uses: ./.github/actions/msgraft
        with:
          access-token: ${{ steps.access-token.outputs.access_token }}

