---
name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  - push
  - workflow_dispatch
permissions:
  id-token: write
  contents: read
  packages: read
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    env:
      no_changes: 'false'
      array: "[]"
    steps:
      - run: echo "fromJson('[false]').*"
        if: fromJson('[false]').*
      - run: echo "fromJson('[1]').*"
        if: fromJson('[1]').*
      - run: echo "fromJson('[]').*"
        if: fromJson('[]').*
      - run: echo "fromJson('[]') == fromJson('[]')"
        if: fromJson('[]') == fromJson('[]')
      - run: echo "fromJson('[]') == fromJson('[1]')"
        if: fromJson('[]') == fromJson('[1]')
      - run: echo "fromJson('[]') == fromJson('[1]')"
        if: fromJson('[]') == fromJson('[1]')
      - run: echo "join(fromJson('[]'), '') == ''"
        if: join(fromJson('[]'), '') == ''
      - run: echo "join(fromJson('[1]'), '') == ''"
        if: join(fromJson('[1]'), '') == ''
      - run: echo asdf
        if: >
          ${{
            !false
            && env.no_changes == 'false'
            && join(fromJson(env.array), '') == ''
          }}
