name: Merge queue
on:
  merge_group:
    types: [checks_requested]
    branches: [main]
jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.init.outputs.modules }}
    steps:
      - id: init
        run: |
          echo 'modules<<EOF'
          cat <<EOF
          ["foo", "bar", "baz"]
          EOF
          echo 'EOF'
  deploy:
    runs-on: ubuntu-latest
    needs: init
    strategy:
      matrix:
        module: ${{ fromJson(needs.init.outputs.modules) }}
    steps:
      - run: |
          echo "$module"
        env:
          module: ${{ matrix.module }}

