name: Merge queue
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  merge_group:
    types:
      - checks_requested
jobs:
  gate:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.orchestrate.outputs.modules }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: '2'
      - id: orchestrate
        if: ${{ github.event_name == 'merge_group' }}
        run: |
          set -euo pipefail
          set -x
          selected_modules="$(<config.sandbox.yaml yq -o json | jq '.environment.selected[]' -r)"
          changed_modules="$(
            git diff --name-only HEAD^ \
            | (grep -o -F "$selected_modules" || true) \
            | LC_ALL=C sort -u
          )"
          (
            echo 'modules<<EOF'
            echo "$changed_modules" | jq -R 'select(length != 0)' | jq -s -c
            echo 'EOF'
          ) >> "$GITHUB_OUTPUT"
  deploy:
    runs-on: ubuntu-latest
    needs: gate
    if: ${{ needs.gate.outputs.modules != null && join(fromJson(needs.gate.outputs.modules)) != '' }}
    strategy:
      matrix:
        module: ${{ fromJson(needs.gate.outputs.modules) }}
    steps:
      - run: |
          echo "$module"
        env:
          module: ${{ matrix.module }}

