---
name: powershell-install-module-test
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  - workflow_dispatch
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - shell: pwsh
        run: |
          Install-Module -RequiredVersion "2.28.0" -Force Microsoft.Graph.Authentication
          Install-Module -RequiredVersion "2.28.0" -Force Microsoft.Graph.Applications
          Install-Module -RequiredVersion "2.28.0" -Force Microsoft.Graph.Groups
          Install-Module -RequiredVersion "2.28.0" -Force Microsoft.Graph.DirectoryObjects

          Get-InstalledModule | Select Name, Version

